[package]
name = "nkcore"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[features]
default = []
debug = ["nkcore-debug"]
winit = ["nkcore-windows/winit"]

[dependencies]
nkcore-base = { workspace = true }
nkcore-debug = { workspace = true, optional = true }

[target.'cfg(windows)'.dependencies]
nkcore-windows = { workspace = true }
