[package]
name = "nkcore-windows"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }

[lints]
workspace = true

[features]
default = []
winit = ["dep:winit"]
d3d11 = [
    "windows/Win32_Graphics_Dxgi_Common",
    "windows/Win32_Graphics_Dxgi",
    "windows/Win32_Graphics_Direct3D",
    "windows/Win32_Graphics_Direct3D11",
]

process-tree = ["dep:win32job"]

[dependencies]
nkcore = { workspace = true }

pretty_env_logger = "0.5.0"
raw-window-handle = "0.6.2"
win32job = { version = "2.0.3", optional = true }
windows = { workspace = true }

[dependencies.winit]
version = "0.30.13"
default-features = false
features = ["rwh_06"]
optional = true
