[package]
name = "nkcore-windows"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[features]
default = []
winit = ["dep:winit"]

[dependencies]
pretty_env_logger = "0.5.0"
raw-window-handle = "0.6.2"
windows = { version = "0.62.2", features = ["Win32_Foundation"] }

[dependencies.winit]
version = "0.30.12"
default-features = false
features = ["rwh_06"]
optional = true
