[package]
name = "winrt-capture"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
nkcore-windows = { workspace = true, features = ["d3d11", "debug"]}

windows = { workspace = true, features = [
    "Graphics_Capture",
    "Graphics_DirectX",
    "Graphics_DirectX_Direct3D11",
    "UI",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_WinRT_Direct3D11",
]}
