[package]
name = "nkcore-macros"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
darling = "0.24.0"
paste = "1.0.15"
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = "3.0.3"
